version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend

  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
